
logging.level.org.bees.optimizer.service: DEBUG
server:
  port: 8888
#  socket.endpoint: ws://172.30.9.50:8080/race
org.bees:
  gamma: 1.0
  max_recursion_number: 3
spring:
  profiles:
    active: markov